### ISSUE TITLE
amebadplus  captive_portal example not  Successfully run

### ISSUE THREAD

**Issue by cheng5230** [Ameba-AIoT/ameba-rtos#49]
sdk commit is 87476980d8544c5b42dbc3e1c87b3d02a5ee6e82 (v1.0)
The following are the steps for reproducing
1. in amebadplus_gcc_project 
2. make all EXAMPLE=captive_portal
3. Burn firmware to run

![image](https://github.com/user-attachments/assets/81c6565d-f40a-418c-b143-b3991aebd280)
**Blocked at the location port_netconn_accept**

![image](https://github.com/user-attachments/assets/13014c59-a0cf-4d06-8ed7-2eb98ebce4c6)

**Comment by cjox** [comment]
Hi @cheng5230 

I have test release/v1.0 87476980d8544c5b42dbc3e1c87b3d02a5ee6e82 captive_portal example, it works fine ~~
below is the running logs:
[branch-1.0-captive-portal-test-log1.txt](https://github.com/user-attachments/files/17696134/branch-1.0-captive-portal-test-log1.txt)
and this is the firmware, please try it at your hardware enviroment.
[branch-1.0-captive-portal.zip](https://github.com/user-attachments/files/17696256/branch-1.0-captive-portal.zip)

at the end of the logs you provided, it indicates that the smart phone have connected with the DUT's softap, please make sure your smart phone's wifi have obtained an IP, such as 192.168.43.xx
if you have got an IP, please try to open 192.168.43.1 in your internet browser.

thanks

**Comment by cheng5230** [comment]
> Hi @cheng5230
> 
> I have test release/v1.0 [8747698](https://github.com/Ameba-AIoT/ameba-rtos/commit/87476980d8544c5b42dbc3e1c87b3d02a5ee6e82) captive_portal example, it works fine ~~ below is the running logs: [branch-1.0-captive-portal-test-log1.txt](https://github.com/user-attachments/files/17696134/branch-1.0-captive-portal-test-log1.txt) and this is the firmware, please try it at your hardware enviroment. [branch-1.0-captive-portal.zip](https://github.com/user-attachments/files/17696256/branch-1.0-captive-portal.zip)
> 
> at the end of the logs you provided, it indicates that the smart phone have connected with the DUT's softap, please make sure your smart phone's wifi have obtained an IP, such as 192.168.43.xx if you have got an IP, please try to open 192.168.43.1 in your internet browser.
> 
> thanks
hi cjox
I open 192.168.43.1 in your internet browser，show normal web UI.
How to configure automatically redirect to the browser and display a web page after a successful connection
not manual open 192.168.43.1 in your internet browser.

**Comment by cheng5230** [comment]
Hi cjox
I open 192.168.43.1 in your internet browser，show normal web UI.
How to configure automatically redirect to the browser and display a web page after a successful connection
not manual open 192.168.43.1 in your internet browser.

**Comment by cjox** [comment]
Hi @cheng5230 

I got your concern.
please follow the readme.txt in the example folder, modify dhcps.h as below:
	**2.Enable captive portal.
		[dhcps.h]:
			#define CONFIG_ENABLE_CAPTIVE_PORTAL  1**
then you will got automatically redirect to the portal page.

thanks

**Comment by cheng5230** [comment]
Hi [cjox](https://github.com/Ameba-AIoT/ameba-rtos/issues/49#issuecomment-2468018163)
i test succeed
thanks！

**Comment by cheng5230** [comment]
Hi [[cjox]](https://github.com/cjox)

After the ap hotspot connection is successful, the IP address of the device is displayed.
![image](https://github.com/user-attachments/assets/12f21c40-88b2-4183-9e7e-0a73bdc8f9a5)

I useing AT+WLSTATE query，no display device IP
![image](https://github.com/user-attachments/assets/b44970c4-f8f9-4a4b-9c28-0fe313b6e25f)

There are have related API to display  device IP ？
thanks！

**Comment by cjox** [comment]
Hi @cheng5230 
I think this is another topic
Could you please open another issue and close this one ?

I will study with the new issue ASAP

thanks
