### ISSUE TITLE
BLE Examples in AmebaDplus

### ISSUE THREAD

**Issue by fahar-cielo** [Ameba-AIoT/ameba-rtos#60]
Hi, 

Can you share any document which defines Bluetooth API used by AmebaDplus, 

I cant find it in ameba documentation. Moreover, Examples given in component/bluetooth/example are bit different from application and peripheral examples. I tried to examples but couldnt do it by `make EXAMPLE=ble_periphreal all`.

Then I tried porting code to src/main and resolved some dependencies errors like cannot find osif.h and other header files, I placed all required header files in project/inc. Now new errors appear which seems to be due to missing source/ not found...Is not that dependency tree should be resolved by sdk?? Or I am doing something wrong?

![image](https://github.com/user-attachments/assets/033b40b2-641d-438b-a4ef-9a30bb5c5111)

**Comment by zs123321** [comment]
You can go to this directory of“ ameba-rtos/amebadplus_gcc_project”  in the SDK，then  type "make menuconfig"and enbale BT，open ble peripheral or central demo，referring to the following  figures，finally，save and exit menuconnfig，type “make all" to build image，after burn image to flash，reset the board，you can type atcmd to init ble a'ccording to atcmd manual，link:https://ameba-aiot.github.io/ameba-iot-docs/amebalite/en/latest/ameba/en/at_command/src/bluetooth_at_command.html
<img width="535" alt="111" src="https://github.com/user-attachments/assets/c3d4d7eb-80ba-49fb-8c5b-dd3bd5a1c44b" />
<img width="509" alt="222" src="https://github.com/user-attachments/assets/7b5ab92f-ebd1-4a4c-afb0-d6f08bf82750" />

**Comment by fahar-cielo** [comment]
secondly, I want to build my custom application i dont want to use at commands, for that I cant find api reference

**Comment by fahar-cielo** [comment]
@zs123321 yes I exactly followed this documentation, I am using windows 11, 

here are the details: https://github.com/Ameba-AIoT/ameba-rtos/issues/59

**Comment by zs123321** [comment]
Hi
After clone SDK,type  make all，please  attach  screenshot of the compile result  
in addition，have you installed every one  required for the following pictures
<img width="519" alt="333" src="https://github.com/user-attachments/assets/37a05ad4-a8cf-4a1f-9010-1cd82de92c76" />

**Comment by fahar-cielo** [comment]
@zs123321 Thanks, But I shifted to linux ubuntu, was facing problem setting up menuconfig and ncurses on windows 11. On Ubuntu everything works as expected. 

However I just have a simple question now, I want to develop a custom ble application without at commands, is there any examples or **api reference** available? I know one document is available showing AT commands to control ble but I want ble component api reference to init, deinit, start, resgister services etc.
